export const DEPARTMENTS = [
  "IT",
  "Human Resources",
  "Finance",
  "Marketing",
  "Sales",
  "Operations",
  "Legal",
  "Customer Service",
  "Research & Development",
  "Quality Assurance",
  "Manufacturing",
  "Logistics",
  "Procurement",
  "Executive",
  "Other",
] as const;

export const DEPARTMENT_COLORS = {
  IT: "#007bff",
  "Human Resources": "#28a745",
  Finance: "#ffc107",
  Marketing: "#e83e8c",
  Sales: "#fd7e14",
  Operations: "#6f42c1",
  Legal: "#dc3545",
  "Customer Service": "#20c997",
  "Research & Development": "#17a2b8",
  "Quality Assurance": "#6c757d",
  Manufacturing: "#343a40",
  Logistics: "#f8f9fa",
  Procurement: "#495057",
  Executive: "#212529",
  Other: "#6c757d",
} as const;

export const DEPARTMENT_ICONS = {
  IT: "FaLaptopCode",
  "Human Resources": "FaUsers",
  Finance: "FaDollarSign",
  Marketing: "FaBullhorn",
  Sales: "FaHandshake",
  Operations: "FaCogs",
  Legal: "FaGavel",
  "Customer Service": "FaHeadset",
  "Research & Development": "FaFlask",
  "Quality Assurance": "FaCheckDouble",
  Manufacturing: "FaIndustry",
  Logistics: "FaTruck",
  Procurement: "FaShoppingCart",
  Executive: "FaUserTie",
  Other: "FaBuilding",
} as const;

export const DEPARTMENT_ABBREVIATIONS = {
  IT: "IT",
  "Human Resources": "HR",
  Finance: "FIN",
  Marketing: "MKT",
  Sales: "SALES",
  Operations: "OPS",
  Legal: "LEGAL",
  "Customer Service": "CS",
  "Research & Development": "R&D",
  "Quality Assurance": "QA",
  Manufacturing: "MFG",
  Logistics: "LOG",
  Procurement: "PROC",
  Executive: "EXEC",
  Other: "OTHER",
} as const;
