import { Permission } from "../types";

export const PERMISSION_LABELS = {
  [Permission.TICKET_CREATE]: "Create Tickets",
  [Permission.TICKET_VIEW]: "View Tickets",
  [Permission.TICKET_UPDATE]: "Update Tickets",
  [Permission.TICKET_DELETE]: "Delete Tickets",
  [Permission.TICKET_ASSIGN]: "Assign Tickets",
  [Permission.TICKET_RESOLVE]: "Resolve Tickets",
  [Permission.ASSET_CREATE]: "Create Assets",
  [Permission.ASSET_VIEW]: "View Assets",
  [Permission.ASSET_UPDATE]: "Update Assets",
  [Permission.ASSET_DELETE]: "Delete Assets",
  [Permission.USER_CREATE]: "Create Users",
  [Permission.USER_VIEW]: "View Users",
  [Permission.USER_UPDATE]: "Update Users",
  [Permission.USER_DELETE]: "Delete Users",
  [Permission.KNOWLEDGE_CREATE]: "Create Knowledge Articles",
  [Permission.KNOWLEDGE_VIEW]: "View Knowledge Base",
  [Permission.KNOWLEDGE_UPDATE]: "Update Knowledge Articles",
  [Permission.KNOWLEDGE_DELETE]: "Delete Knowledge Articles",
  [Permission.KNOWLEDGE_PUBLISH]: "Publish Knowledge Articles",
  [Permission.REPORT_VIEW]: "View Reports",
  [Permission.REPORT_CREATE]: "Create Reports",
  [Permission.REPORT_EXPORT]: "Export Reports",
  [Permission.NETWORK_VIEW]: "View Network Status",
  [Permission.NETWORK_MANAGE]: "Manage Network Devices",
  [Permission.ADMIN_SETTINGS]: "Admin Settings",
  [Permission.ADMIN_USERS]: "Admin User Management",
  [Permission.ADMIN_SYSTEM]: "Admin System Management",
} as const;

export const PERMISSION_CATEGORIES = {
  tickets: [
    Permission.TICKET_CREATE,
    Permission.TICKET_VIEW,
    Permission.TICKET_UPDATE,
    Permission.TICKET_DELETE,
    Permission.TICKET_ASSIGN,
    Permission.TICKET_RESOLVE,
  ],
  assets: [
    Permission.ASSET_CREATE,
    Permission.ASSET_VIEW,
    Permission.ASSET_UPDATE,
    Permission.ASSET_DELETE,
  ],
  users: [
    Permission.USER_CREATE,
    Permission.USER_VIEW,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
  ],
  knowledge: [
    Permission.KNOWLEDGE_CREATE,
    Permission.KNOWLEDGE_VIEW,
    Permission.KNOWLEDGE_UPDATE,
    Permission.KNOWLEDGE_DELETE,
    Permission.KNOWLEDGE_PUBLISH,
  ],
  reports: [
    Permission.REPORT_VIEW,
    Permission.REPORT_CREATE,
    Permission.REPORT_EXPORT,
  ],
  network: [Permission.NETWORK_VIEW, Permission.NETWORK_MANAGE],
  admin: [
    Permission.ADMIN_SETTINGS,
    Permission.ADMIN_USERS,
    Permission.ADMIN_SYSTEM,
  ],
} as const;

export const PERMISSION_DESCRIPTIONS = {
  [Permission.TICKET_CREATE]: "Ability to create new support tickets",
  [Permission.TICKET_VIEW]: "Ability to view ticket details and lists",
  [Permission.TICKET_UPDATE]: "Ability to update existing tickets",
  [Permission.TICKET_DELETE]: "Ability to delete tickets",
  [Permission.TICKET_ASSIGN]: "Ability to assign tickets to users",
  [Permission.TICKET_RESOLVE]: "Ability to resolve and close tickets",
  [Permission.ASSET_CREATE]: "Ability to add new assets to inventory",
  [Permission.ASSET_VIEW]: "Ability to view asset information",
  [Permission.ASSET_UPDATE]: "Ability to update asset information",
  [Permission.ASSET_DELETE]: "Ability to remove assets from inventory",
  [Permission.USER_CREATE]: "Ability to create new user accounts",
  [Permission.USER_VIEW]: "Ability to view user information",
  [Permission.USER_UPDATE]: "Ability to update user information",
  [Permission.USER_DELETE]: "Ability to delete user accounts",
  [Permission.KNOWLEDGE_CREATE]: "Ability to create knowledge base articles",
  [Permission.KNOWLEDGE_VIEW]: "Ability to view knowledge base content",
  [Permission.KNOWLEDGE_UPDATE]: "Ability to update knowledge base articles",
  [Permission.KNOWLEDGE_DELETE]: "Ability to delete knowledge base articles",
  [Permission.KNOWLEDGE_PUBLISH]: "Ability to publish knowledge base articles",
  [Permission.REPORT_VIEW]: "Ability to view reports and analytics",
  [Permission.REPORT_CREATE]: "Ability to create custom reports",
  [Permission.REPORT_EXPORT]: "Ability to export reports to various formats",
  [Permission.NETWORK_VIEW]: "Ability to view network monitoring data",
  [Permission.NETWORK_MANAGE]: "Ability to manage network devices and settings",
  [Permission.ADMIN_SETTINGS]: "Ability to access admin settings",
  [Permission.ADMIN_USERS]: "Ability to manage users and roles",
  [Permission.ADMIN_SYSTEM]: "Ability to manage system configuration",
} as const;
